-- MySQL Script generated by MySQL Workbench
-- Thu Oct 24 00:47:02 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema codeVenture
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `codeVenture` ;

-- -----------------------------------------------------
-- Schema codeVenture
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `codeVenture` DEFAULT CHARACTER SET utf8 ;
USE `codeVenture` ;

-- -----------------------------------------------------
-- Table `codeVenture`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codeVenture`.`users` ;

CREATE TABLE IF NOT EXISTS `codeVenture`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(255) NULL,
  `created_at` DATETIME NULL DEFAULT NOW(),
  `updated_at` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codeVenture`.`credentials`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codeVenture`.`credentials` ;

CREATE TABLE IF NOT EXISTS `codeVenture`.`credentials` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `created_at` DATETIME NULL DEFAULT NOW(),
  `updated_at` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_credentials_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `codeVenture`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_credentials_users_idx` ON `codeVenture`.`credentials` (`user_id` ASC) ;


-- -----------------------------------------------------
-- Table `codeVenture`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codeVenture`.`roles` ;

CREATE TABLE IF NOT EXISTS `codeVenture`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `roles` VARCHAR(255) NULL,
  `created_at` DATETIME NULL DEFAULT NOW(),
  `updated_at` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_roles_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `codeVenture`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_roles_users1_idx` ON `codeVenture`.`roles` (`user_id` ASC) ;


-- -----------------------------------------------------
-- Table `codeVenture`.`lessons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codeVenture`.`lessons` ;

CREATE TABLE IF NOT EXISTS `codeVenture`.`lessons` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role_id` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `description` VARCHAR(255) NULL,
  `created_at` DATETIME NULL DEFAULT NOW(),
  `updated_at` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_groups_teachers1`
    FOREIGN KEY (`role_id`)
    REFERENCES `codeVenture`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_groups_teachers1_idx` ON `codeVenture`.`lessons` (`role_id` ASC) ;


-- -----------------------------------------------------
-- Table `codeVenture`.`levels`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codeVenture`.`levels` ;

CREATE TABLE IF NOT EXISTS `codeVenture`.`levels` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lesson_id` INT NOT NULL,
  `level_name` VARCHAR(45) NULL,
  `content` BLOB NULL,
  `isTask` TINYINT NULL,
  `created_at` DATETIME NULL DEFAULT NOW(),
  `updated_at` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_challenges_groups1`
    FOREIGN KEY (`lesson_id`)
    REFERENCES `codeVenture`.`lessons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_challenges_groups1_idx` ON `codeVenture`.`levels` (`lesson_id` ASC) ;


-- -----------------------------------------------------
-- Table `codeVenture`.`task_answers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codeVenture`.`task_answers` ;

CREATE TABLE IF NOT EXISTS `codeVenture`.`task_answers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `answers` BLOB NULL,
  `user_id` INT NOT NULL,
  `task_id` INT NOT NULL,
  `lesson_id` INT NOT NULL,
  `created_at` DATETIME NULL DEFAULT NOW(),
  `updated_at` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_challenge_answers_materials1`
    FOREIGN KEY (`task_id`)
    REFERENCES `codeVenture`.`levels` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_challenge_answers_lessons1`
    FOREIGN KEY (`lesson_id`)
    REFERENCES `codeVenture`.`lessons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_task_answers_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `codeVenture`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_challenge_answers_materials1_idx` ON `codeVenture`.`task_answers` (`task_id` ASC) ;

CREATE INDEX `fk_challenge_answers_lessons1_idx` ON `codeVenture`.`task_answers` (`lesson_id` ASC) ;

CREATE INDEX `fk_task_answers_users1_idx` ON `codeVenture`.`task_answers` (`user_id` ASC) ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
