-- MySQL Script generated by MySQL Workbench
-- Sun Sep  8 01:43:50 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';


USE `codeVenture` ;

-- -----------------------------------------------------
-- Table `codeVenture`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codeVenture`.`users` ;

CREATE TABLE IF NOT EXISTS `codeVenture`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(255) NULL,
  `created_at` DATETIME NULL DEFAULT NOW(),
  `updated_at` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codeVenture`.`credentials`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codeVenture`.`credentials` ;

CREATE TABLE IF NOT EXISTS `codeVenture`.`credentials` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `created_at` DATETIME NULL DEFAULT NOW(),
  `updated_at` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`id`),
  INDEX `fk_credentials_users_idx` (`user_id` ASC) ,
  CONSTRAINT `fk_credentials_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `codeVenture`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codeVenture`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codeVenture`.`roles` ;

CREATE TABLE IF NOT EXISTS `codeVenture`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `roles` VARCHAR(255) NULL,
  `created_at` DATETIME NULL DEFAULT NOW(),
  `updated_at` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`id`),
  INDEX `fk_teachers_users1_idx` (`user_id` ASC) ,
  CONSTRAINT `fk_teachers_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `codeVenture`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codeVenture`.`groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codeVenture`.`groups` ;

CREATE TABLE IF NOT EXISTS `codeVenture`.`groups` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role_id` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `description` VARCHAR(255) NULL,
  `created_at` DATETIME NULL DEFAULT NOW(),
  `updated_at` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`id`),
  INDEX `fk_groups_teachers1_idx` (`role_id` ASC) ,
  CONSTRAINT `fk_groups_teachers1`
    FOREIGN KEY (`role_id`)
    REFERENCES `codeVenture`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codeVenture`.`specific_groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codeVenture`.`specific_groups` ;

CREATE TABLE IF NOT EXISTS `codeVenture`.`specific_groups` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `group_id` INT NOT NULL,
  `created_at` DATETIME NULL DEFAULT NOW(),
  `updated_at` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`id`),
  INDEX `fk_specific_groups_groups1_idx` (`group_id` ASC) ,
  INDEX `fk_specific_groups_users1_idx` (`user_id` ASC) ,
  CONSTRAINT `fk_specific_groups_groups1`
    FOREIGN KEY (`group_id`)
    REFERENCES `codeVenture`.`groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_specific_groups_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `codeVenture`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codeVenture`.`challenges`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codeVenture`.`challenges` ;

CREATE TABLE IF NOT EXISTS `codeVenture`.`challenges` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `group_id` INT NOT NULL,
  `challenge_name` VARCHAR(45) NULL,
  `description` TEXT NULL,
  `created_at` DATETIME NULL DEFAULT NOW(),
  `updated_at` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`id`),
  INDEX `fk_challenges_groups1_idx` (`group_id` ASC) ,
  CONSTRAINT `fk_challenges_groups1`
    FOREIGN KEY (`group_id`)
    REFERENCES `codeVenture`.`groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codeVenture`.`challenge_answers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codeVenture`.`challenge_answers` ;

CREATE TABLE IF NOT EXISTS `codeVenture`.`challenge_answers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `specific_group_id` INT NOT NULL,
  `challenge_id` INT NOT NULL,
  `created_at` DATETIME NULL DEFAULT NOW(),
  `updated_at` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`id`),
  INDEX `fk_challenge_answers_specific_groups1_idx` (`specific_group_id` ASC) ,
  INDEX `fk_challenge_answers_challenges1_idx` (`challenge_id` ASC) ,
  CONSTRAINT `fk_challenge_answers_specific_groups1`
    FOREIGN KEY (`specific_group_id`)
    REFERENCES `codeVenture`.`specific_groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_challenge_answers_challenges1`
    FOREIGN KEY (`challenge_id`)
    REFERENCES `codeVenture`.`challenges` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codeVenture`.`achievements`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codeVenture`.`achievements` ;

CREATE TABLE IF NOT EXISTS `codeVenture`.`achievements` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `description` VARCHAR(255) NULL,
  `created_at` DATETIME NULL DEFAULT NOW(),
  `updated_at` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codeVenture`.`achieved_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codeVenture`.`achieved_users` ;

CREATE TABLE IF NOT EXISTS `codeVenture`.`achieved_users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `achievement_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `created_at` DATETIME NULL DEFAULT NOW(),
  `updated_at` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`id`),
  INDEX `fk_achieved_users_achievements1_idx` (`achievement_id` ASC) ,
  INDEX `fk_achieved_users_users1_idx` (`user_id` ASC) ,
  CONSTRAINT `fk_achieved_users_achievements1`
    FOREIGN KEY (`achievement_id`)
    REFERENCES `codeVenture`.`achievements` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_achieved_users_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `codeVenture`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
